### ISSUE TITLE
Remote Play window not found ?

### ISSUE THREAD

**Issue by marlos45** [4A47/pesbot#2]
Hey thx for this nice program, i want to try it but i have this error when i lauch the command pesbot.exe sim "Remote Play window not found"

Anyone have solution for solve it ? maybe it's because i have ps4 remote play in french on french system ?

If anyone can help me to solve this problem it will be really nice :)

**Comment by marlos45** [comment]
So i solve it for foreigner you need to put windows in english for the bot start but now i have another problem lol

**Comment by 4A47** [comment]
Added support for French, Spanish, Italian languages.
